- set_fact:
    device: "{{ swvars[inventory_hostname] }}"
    bgp: "{{ swvars[inventory_hostname].bgp }}"
    vxlan: "{{ swvars[inventory_hostname].vxlan }}"

- name: Set up BGP unnumbered via template
  nclu:
    template: |
      add bgp autonomous-system {{ bgp.asn }}
      add bgp router-id {{ device.loopback|replace("/32", "") }}
      add bgp bestpath as-path multipath-relax
      add bgp bestpath compare-routerid
      add bgp neighbor fabric peer-group
      add bgp neighbor fabric remote-as external
      add bgp neighbor fabric description Clos Fabric
      add bgp neighbor fabric capability extended-nexthop
      
      {% if bgp.fabints is defined %}
      add bgp neighbor {{ bgp.fabints }} peer-group fabric
      {% endif %}
      
      {% if bgp.otherints is defined %}
      add bgp neighbor {{ bgp.otherints }} interface remote-as external
      {% endif %}
      
      {% if vxlan.anycastip is defined %}
      add bgp ipv4 unicast network {{ vxlan.anycastip }}
      {% endif %}
      
      {% if vxlan.vtep is defined %}
      add bgp l2vpn evpn neighbor fabric activate
      {%	if vxlan.vtep == 'yes' %}
      add bgp l2vpn evpn advertise-all-vni
      {%	endif %}
      {% endif %}
      
      add routing route-map LOOPBACK permit 10 match interface lo
      add bgp ipv4 unicast redistribute connected route-map LOOPBACK
    atomic: true
